name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-image:latest

  push_to_gitea:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Push to Gitea
        env:
          GITEA_SERVER: ${{ secrets.ADDRESS_GITEA_SERVER }}
          GITEA_TOKEN: ${{ secrets.REPO_GITEA_TOKEN }}
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/my-image:latest ${GITEA_SERVER}/my-repo/my-image:latest
          docker push ${GITEA_SERVER}/my-repo/my-image:latest
