name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env: 
      GITEA_SERVER: https://git.rehounou.ca
      GITEA_REGISTRY: git.rehounou.ca
      GITEA_TOKEN: ${{ secrets.REPO_GITEA_TOKEN }}
      PROJECT_NAME: cal_heatmap

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/cal_heatmap:latest

      - name: Log in to Gitea Docker Registry
        run: |
          echo ${{ secrets.REPO_GITEA_TOKEN }} | docker login ${{ env.GITEA_REGISTRY }} -u ${{ secrets.REPO_USERNAME }} --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.GITEA_REGISTRY }}/${{ secrets.REPO_USERNAME }}/cal_heatmap:latest
